project:
  type: website

website:
  page-navigation: true
  title: "BEE 4850 - Spring 2024"
  description: "Homepage for BEE 4850/5850, Simulation Methods for Environmental Data Analysis, at Cornell University, Spring 2024."
  site-url: "https://viveks.me/simulation-data-analysis"

  repo-url: https://github.com/vsrikrish/simulation-data-analysis

  open-graph: true

  page-footer:
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}}  by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      See the [About page](/about.html) page for credit information.

  sidebar:
    style: docked
    align: center
    background: "#222222"
    logo: _assets/logos/cornell_logo_simple_b31b1b.svg
    title: "{{< var course.number >}}: {{< course.title >}}"
    search: true
    tools: 
      - icon: github
        href: https://github.com/vsrikrish/simulation-data-analysis
        text: "Github Repository"
      - icon: journal-check
        href: https://canvas.cornell.edu
        text: "Canvas"
      - icon: chat-fill
        text: "Ed Discussion"
        url: https://edstem.org
      - icon: bar-chart-fill
        text: "Gradescope"
        url: https://gradescope.com
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: index.qmd
            text: Overview
          - href: syllabus.qmd
            text: Syllabus
          - href: schedule.qmd
            text: Class Schedule
      - section: assignments.qmd
        contents:
          - href: assignments/hw1/hw1.qmd
            text: Homework 1
      - section: "Julia Tutorials"
        contents:
          - href: tutorials/julia-basics.qmd
            text: Julia Basics
          - href: tutorials/julia-plots.qmd
            text: Making Plots
          - href: tutorials/turing-mcmc.qmd
            text: MCMC with Turing
format:
  html:
    theme: 
      light: [cosmo, sass/theme.scss]
      dark: [cosmo, sass/theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: margin
    citation-location: margin
    code-annotations: select

bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl
execute:
  freeze: auto
  

