project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "BEE 4850 - Spring 2025"
  description: "Homepage for BEE 4850/5850, Environmental Data Analysis and Simulation, at Cornell University, Spring 2025."
  site-url: "https://viveks.me/simulation-data-analysis"

  repo-url: https://github.com/vsrikrish/simulation-data-analysis

  open-graph: true

  page-footer:
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}}  by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}).
      See the [About](/about.html) page for credit information.<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

  sidebar:
    style: docked
    align: center
    border: true
    logo: _assets/logos/cornell_logo_simple_b31b1b.svg
    title: "{{< var course.number >}}"
    search: true
    tools: 
      - icon: github
        href: https://github.com/vsrikrish/simulation-data-analysis
        text: "Github Repository"
      - icon: journal-check
        href: https://canvas.cornell.edu
        text: "Canvas"
      - icon: chat-fill
        text: "Ed Discussion"
        url: https://edstem.org
      - icon: bar-chart-fill
        text: "Gradescope"
        url: https://gradescope.com
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: index.qmd
            text: Overview
          - href: syllabus.qmd
            text: Syllabus
          - href: schedule.qmd
            text: Class Schedule
      - section: "Weeks"
        contents:
          - href: weeks/week01.qmd
            text: "Week 1"
          - href: weeks/week02.qmd
            text: "Week 2"
      - section: homework.qmd
        text: "Homework"
        contents:
          - href: policies/homework.qmd
            text: "Homework Policies"
          - href: rubrics/standard.qmd
            text: "Standard Rubric"
          - href: hw/hw01/hw01.qmd
            text: "Homework 01"
      - project.qmd
      - lit_critique.qmd
      - section: "Julia Tutorials"
        contents:
          - href: tutorials/julia-basics.qmd
            text: Julia Basics
          - href: tutorials/julia-plots.qmd
            text: Making Plots
          - href: tutorials/turing-mcmc.qmd
            text: MCMC with Turing
format:
  html:
    grid:
      gutter-width: 1em
    theme: 
      [simplex, sass/theme.scss]
    mainfont: "Atkinson Hyperlegible"
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: margin
    citation-location: margin
    code-annotations: select

bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl
execute:
  freeze: auto

