---
title: "Week 7 Information"
---

## Lectures

- [Monte Carlo](../slides/lecture07-1-monte-carlo.qmd)
- [The Bootstrap](../slides/lecture07-2-bootstrap.qmd)

## Homework

- [Homework 3](../hw/hw03/hw03.qmd) due 3/14/25 by 9PM.
- [Solutions for Homework 2](../solutions/hw/hw02/hw02.qmd) available.

## Readings

  - Bankes, S. (1993). Exploratory modeling for policy analysis. Operations Research, 41(3), 435–449. <https://doi.org/10.1287/opre.41.3.435>

  As you're reading, please use the collaborative annotation in Canvas to make notes and read and respond to others' thoughts and questions. We will discuss the paper in the 03/10 class period. You will be graded based on annotation and participation in the discussion.

  In particular, please focus on:

  * What are the differences between consolidative and exploratory modeling?
  * What is the relationship between exploratory modeling and the types of model-based analyses we are discussing in class?
  * How can exploratory modeling be used in conjunction with or instead of Monte Carlo when we don't have well-defined input distributions?
  * How might sensitivity analysis fit into our modeling workflows?
  * How do different exploratory modeling types reflect different goals and questions, and what are the implications for modeling or data analysis approaches?

## Quiz

- Quiz due Monday.