---
title: "Week 8 Information"
---

## Lectures

- [The Parametric Bootstrap](../slides/lecture08-1-parametric-bootstrap.qmd)
- [Bayesian Computing](../slides/lecture08-2-bayesian-computation.qmd)

## Homework

- [Homework 3](../hw/hw03/hw03.qmd) due 3/14/25 by 9PM.

## Readings

- Ruckert, K. L., Guan, Y., Bakker, A. M. R., Forest, C. E., & Keller, K. (2017). The effects of time-varying observation errors on semi-empirical sea-level projections. *Climatic Change*, 140(3–4), 349–360. <https://doi.org/10.1007/s10584-016-1858-z>


  As you're reading, please use the collaborative annotation in Canvas to make notes and read and respond to others' thoughts and questions. We will discuss the paper in the 03/17 class period. You will be graded based on annotation and participation in the discussion.

  In particular, please focus on:

  * What are the reasons why one might use the different inference approaches compared in the paper?
  * What are the practical implications of the varying methods?

## Quiz

- Quiz due Monday.