---
title: "Week 9 Information"
---

## Lectures

- [Markov Chain Monte Carlo](../slides/lecture09-1-mcmc.qmd)
- [Predictive Model Assessments](../slides/lecture09-2-model-skill.qmd)

## Homework

- Homework 4 will be assigned this week, due 4/11 at 9pm.

## Readings

- Clark, M. P., Vogel, R. M., Lamontagne, J. R., Mizukami, N., Knoben, W. J. M., Tang, G., et al. (2021). The abuse of popular performance metrics in hydrologic modeling. Water Resources Research, 57(9). <https://doi.org/10.1029/2020wr029001>

  As you're reading, please use the collaborative annotation in Canvas to make notes and read and respond to others' thoughts and questions. We will discuss the paper in the 03/24 class period. You will be graded based on annotation and participation in the discussion.

  In particular, please focus on:

  * What are the practical implications of the identified uncertainties in the analyzed performance metrics? Do you agree with the conclusions drawn by the authors?
  * Can you think of analogues in other applications that you're familiar with? 
  * What does this paper suggest about the assessment of environmental model performance?

## Quiz

- No quiz this week.