on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - Spring23

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install Jupyter
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.8.3

      - name: Install IJulia
        run: julia -e 'using Pkg; Pkg.activate("website"); Pkg.instantiate(); Pkg.build("IJulia")'
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: "website"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
